version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=8080
      - PLAYGROUND=true
      - INTROSPECTION=true
    networks:
      fdk:
        aliases:
          - fdk-translations-api
networks:
  fdk:
    name: fdk
